version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.19

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run build

  release:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npx semantic-release

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
